version: "3.9"

services:
  postgres:
    image: postgres:15-alpine
    container_name: warehouse-postgres
    environment:
      POSTGRES_DB: warehouse_db
      POSTGRES_USER: warehouse_user
      POSTGRES_PASSWORD: warehouse_pass
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./backend/services/user-service/sql/schema.sql:/docker-entrypoint-initdb.d/01_user.sql
      - ./backend/services/order-service/sql/schema.sql:/docker-entrypoint-initdb.d/02_order.sql
      - ./backend/services/inventory-service/sql/schema.sql:/docker-entrypoint-initdb.d/03_inventory.sql

  user-service:
    build:
      context: ./backend/services/user-service
    container_name: user-service
    environment:
      HTTP_PORT: 8080
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: warehouse_db
      DB_USER: warehouse_user
      DB_PASSWORD: warehouse_pass
      JWT_SECRET: super-secret
    ports:
      - "8081:8080"
    depends_on:
      - postgres

  inventory-service:
    build:
      context: ./backend/services/inventory-service
    container_name: inventory-service
    environment:
      HTTP_PORT: 8080
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: warehouse_db
      DB_USER: warehouse_user
      DB_PASSWORD: warehouse_pass
      ORDER_SERVICE_URL: http://order-service:8080
      ORDER_CALLBACK_SECRET: local-callback-secret
      CHAOS_ENABLED: "false"
    ports:
      - "8083:8080"
    depends_on:
      - postgres

  order-service:
    build:
      context: ./backend/services/order-service
    container_name: order-service
    environment:
      HTTP_PORT: 8080
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: warehouse_db
      DB_USER: warehouse_user
      DB_PASSWORD: warehouse_pass
      JWT_SECRET: super-secret
      INVENTORY_HTTP_URL: http://inventory-service:8080
      USE_CLOUD_TASKS: "false"
      INVENTORY_WAIT_MS: 15000
      INVENTORY_POLL_MS: 1000
      ORDER_CALLBACK_SECRET: local-callback-secret
    ports:
      - "8082:8080"
    depends_on:
      - postgres
      - inventory-service

  frontend:
    build:
      context: ./frontend
      args:
        VITE_USER_API: http://localhost:8081
        VITE_ORDER_API: http://localhost:8082
        VITE_INVENTORY_API: http://localhost:8083
    container_name: warehouse-frontend
    ports:
      - "8080:8080"
    depends_on:
      - user-service
      - order-service
      - inventory-service

volumes:
  pg_data:
